import { pig_model,
  iron_golem_model,
  blaze_model,
  creeper_model,
  ender_dragon_model,
  enderman_model,
  ghast_model,
  skeleton_model,
  spider_model,
  villager_model,
  wither_model,
  zombie_model,
  pig_pic,
  iron_golem_pic,
  blaze_pic,
  creeper_pic,
  ender_dragon_pic,
  enderman_pic,
  ghast_pic,
  skeleton_pic,
  spider_pic,
  villager_pic,
  wither_pic,
  zombie_pic,
  pig_sound,
  iron_golem_sound,
  blaze_sound,
  creeper_sound,
  ender_dragon_sound,
  enderman_sound,
  ghast_sound,
  skeleton_sound,
  spider_sound,
  villager_sound,
  wither_sound,
  zombie_sound,
  pig_banner,
  iron_golem_banner,
  blaze_banner,
  creeper_banner,
  ender_dragon_banner,
  enderman_banner,
  ghast_banner,
  skeleton_banner,
  spider_banner,
  villager_banner,
  wither_banner,
  zombie_banner
} from "../assets";

export const mob_list = [
    {
      id: "1",
      name: "Pig",
      type: "Passive",
      health: 10,
      damage: "0 (None)",
      behavior: "Follows Player if player holds a carrot",
      habitat: "Everywhere",
      drops: ["Pork Chops"],
      rarity: "Common",
      description: "A pig is a passive mob found commonly in most grass biomes, though they also can also spawn in the Taiga biomes, the Badlands, Savanna, and Jungle biomes with seperate variants. Pigs are a source of porkchops and can be equipped with a saddle to be driven.",
      model: pig_model,
      image: pig_pic,
      banner: pig_banner,
      sound: pig_sound,
      scale: 0.75,
      position: [0, -3, 0],
      rotation: [0, 0, 0],
      weaknesses: ["Fall damage", "Environmental hazards"],
      abilities: ["Eats Grass"]
    },
    {
      id: "2",
      name: "Iron Golem",
      type: "Neutral",
      health: 100,
      damage: "7-21",
      behavior: "Protects villagers and attacks hostile mobs",
      habitat: "Villages",
      drops: ["Iron Ingots", "Poppy"],
      rarity: "Uncommon",
      description: "Iron Golems are utility mobs that protect villagers. They are strong, tall, and can throw enemies into the air.",
      model: iron_golem_model,
      image: iron_golem_pic,
      banner: iron_golem_banner,
      sound: iron_golem_sound,
      scale: 0.8,
      position: [0, 8, 0],
      rotation: [0, 0, 0],
      weaknesses: ["Water", "Cacti"],
      abilities: ["Throwing Attack", "Village Protection"]
    },
    {
      id: "3",
      name: "Creeper",
      type: "Hostile",
      health: 20,
      damage: "49 (Explosion)",
      behavior: "Sneaks up on players and explodes",
      habitat: "Overworld, Dark areas",
      drops: ["Gunpowder"],
      rarity: "Common",
      description: "A hostile mob that silently approaches players and explodes, causing massive damage to players and the environment. Known for its distinctive green pixelated appearance and hissing sound before detonation.",
      model: creeper_model,
      image: creeper_pic,
      banner: creeper_banner,
      sound: creeper_sound,
      scale: 0.8,
      position: [0, -10, 0],
      rotation: [0, 180, 0],
      weaknesses: ["Cats", "Ranged attacks"],
      abilities: ["Explosion", "Silent movement"]
    },
    {
      id: "4",
      name: "Enderman",
      type: "Neutral",
      health: 40,
      damage: "7",
      behavior: "Teleports when attacked or when looked at in the eyes",
      habitat: "The End, Nighttime Overworld",
      drops: ["Ender Pearl"],
      rarity: "Uncommon",
      description: "A tall, dark mob that can teleport and pick up blocks. Becomes hostile when players look directly at its face. Known for its deep vocal sounds and ability to traverse dimensions.",
      model: enderman_model,
      image: enderman_pic,
      banner: enderman_banner,
      sound: enderman_sound,
      scale: 0.65,
      position: [0, 7.5, 0],
      rotation: [0, 0, 0],
      weaknesses: ["Water", "Rain"],
      abilities: ["Teleportation", "Block carrying"]
    },
    {
      id: "5",
      name: "Skeleton",
      type: "Hostile",
      health: 20,
      damage: "2-5 (Arrow)",
      behavior: "Ranged attacks with bows from a distance",
      habitat: "Dark areas, The Nether",
      drops: ["Bone", "Arrow", "Bow"],
      rarity: "Common",
      description: "An undead mob that attacks players with bows and arrows from a distance. Burns in sunlight and can wear armor. Known for its rattling bones and accurate shooting.",
      model: skeleton_model,
      image: skeleton_pic,
      banner: skeleton_banner,
      sound: skeleton_sound,
      scale: 0.74,
      position: [0, 2, 0],
      rotation: [0, 0, 0],
      weaknesses: ["Sunlight", "Smite enchantment"],
      abilities: ["Ranged attacks", "Arrow shooting"]
    },
    {
      id: "6",
      name: "Zombie",
      type: "Hostile",
      health: 20,
      damage: "3",
      behavior: "Chases and attacks players in close range",
      habitat: "Anywhere at night",
      drops: ["Rotten Flesh", "Iron Ingot", "Carrot", "Potato"],
      rarity: "Common",
      description: "A common undead mob that chases players and villagers. Can break down wooden doors and spawn baby zombies. Burns in sunlight and can call for reinforcements.",
      model: zombie_model,
      image: zombie_pic,
      banner: zombie_banner,
      sound: zombie_sound,
      scale: 7,
      position: [0, -10, 0],
      rotation: [0, 10, 0],
      weaknesses: ["Sunlight", "Smite enchantment", "Fire"],
      abilities: ["Door breaking", "Reinforcement calling"]
    },
    {
      id: "7",
      name: "Spider",
      type: "Hostile",
      health: 16,
      damage: "2",
      behavior: "Climbs walls and attacks players at night",
      habitat: "Dark areas, Forests",
      drops: ["String", "Spider Eye"],
      rarity: "Common",
      description: "A hostile mob that can climb walls and jump at players. Becomes neutral during daytime unless provoked. Known for its ability to fit through 1-block high spaces.",
      model: spider_model,
      image: spider_pic,
      banner: spider_banner,
      sound: spider_sound,
      scale: 0.85,
      position: [0, -5, 0],
      rotation: [0, 0, 0],
      weaknesses: ["Sweeping edge", "Bane of Arthropods"],
      abilities: ["Wall climbing", "Jump attacks"]
    },
    {
      id: "8",
      name: "Ender Dragon",
      type: "Boss",
      health: 200,
      damage: "6-15",
      behavior: "Flies around The End and attacks with dragon breath",
      habitat: "The End",
      drops: ["Dragon Egg", "Experience"],
      rarity: "Legendary",
      description: "The final boss of Minecraft, found in The End dimension. Flies around the obsidian pillars and regenerates health from end crystals. Defeating it grants access to the End Cities.",
      model: ender_dragon_model,
      image: ender_dragon_pic,
      banner: ender_dragon_banner,
      sound: ender_dragon_sound,
      scale: 1.0,
      position: [0, 25, 0],
      rotation: [0, 0, 0],
      weaknesses: ["End Crystals destruction", "Beds explosion"],
      abilities: ["Flight", "Dragon breath", "Charged attacks"]
    },
    {
      id: "9",
      name: "Wither",
      type: "Boss",
      health: 300,
      damage: "8 (Wither effect)",
      behavior: "Flies and shoots wither skulls at players",
      habitat: "Player-summoned",
      drops: ["Nether Star"],
      rarity: "Legendary",
      description: "A powerful boss mob created by players using soul sand and wither skeleton skulls. Flies and shoots explosive wither skulls that inflict the wither effect. Known for its devastating area damage.",
      model: wither_model,
      image: wither_pic,
      banner: wither_banner,
      sound: wither_sound,
      scale: 20.0,
      position: [0, 10, 0],
      rotation: [0, 10, 0],
      weaknesses: ["Smite enchantment", "Healing potions"],
      abilities: ["Wither effect", "Explosive skulls", "Flight"]
    },
    {
      id: "10",
      name: "Villager",
      type: "Passive",
      health: 20,
      damage: "0 (None)",
      behavior: "Trades with players and works at job sites",
      habitat: "Villages",
      drops: ["None"],
      rarity: "Common",
      description: "A passive mob that lives in villages and trades with players. Has different professions based on their job site blocks. Can breed and form iron golems for protection.",
      model: villager_model,
      image: villager_pic,
      banner: villager_banner,
      sound: villager_sound,
      scale: 1.5,
      position: [0, -9, 0],
      rotation: [0, 0, 0],
      weaknesses: ["Zombies", "Raids"],
      abilities: ["Trading", "Breeding", "Golem summoning"]
    },
    {
      id: "11",
      name: "Blaze",
      type: "Hostile",
      health: 20,
      damage: "6 (Fireball)",
      behavior: "Flies and shoots fireballs at players",
      habitat: "Nether Fortresses",
      drops: ["Blaze Rod"],
      rarity: "Uncommon",
      description: "A hostile mob found in Nether fortresses that flies and shoots fireballs. Essential for brewing as it drops blaze rods. Takes extra damage from snowballs and water.",
      model: blaze_model,
      image: blaze_pic,
      banner: blaze_banner,
      sound: blaze_sound,
      scale: 0.85,
      position: [0, 10, 0],
      rotation: [0, 0, 0],
      weaknesses: ["Snowballs", "Water", "Bane of Arthropods"],
      abilities: ["Flight", "Fireball shooting", "Fire immunity"]
    },
    {
      id: "12",
      name: "Ghast",
      type: "Hostile",
      health: 10,
      damage: "17 (Explosion)",
      behavior: "Floats and shoots explosive fireballs",
      habitat: "The Nether",
      drops: ["Gunpowder", "Ghast Tear"],
      rarity: "Uncommon",
      description: "A large, floating mob found in the Nether that shoots explosive fireballs. Known for its distinctive crying sounds. Fireballs can be deflected back at them.",
      model: ghast_model,
      image: ghast_pic,
      banner: ghast_banner,
      sound: ghast_sound,
      scale: 2.5,
      position: [0, 38, 0],
      rotation: [0, 0, 0],
      weaknesses: ["Fireball deflection", "Ranged attacks"],
      abilities: ["Flight", "Explosive fireballs", "Crying sounds"]
    }
  ]